name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r sales_agent_api/requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest -q

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Get Docker Hub credentials
        id: kv
        uses: azure/get-keyvault-secrets@v1
        with:
          keyvault: kv-r8fm
          secrets: DOCKERUSERNAME,DOCKERPASSWORD

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ steps.kv.outputs.DOCKERUSERNAME }}
          password: ${{ steps.kv.outputs.DOCKERPASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: sales_agent_api/Dockerfile
          push: true
          tags: ${{ steps.kv.outputs.DOCKERUSERNAME }}/sales-agent-api:latest
